### ISSUE TITLE
[TF2] Do we need float64?

### ISSUE THREAD

**Issue by picciama** [theislab/batchglm#109]
Do we need float64 or would it be sufficient to run the models with float32?
Do you have any experience concerning precision and runtime?
Did you try that in the past maybe?

**Comment by davidsebfischer** [comment]
Is there a difficulty with implementing float64 as an alternative? float32 is fine as a default but there might be cases in whicch float64 is preferable.

**Comment by picciama** [comment]
I am using float64 as default and I wonder whether it is a little bit overkill.

**Comment by davidsebfischer** [comment]
float32 should be default

**Comment by picciama** [comment]
> float32 should be default

This is fixed on the linesearch_tf2 branch. Will close once https://github.com/theislab/batchglm/pull/111 is done.

**Comment by picciama** [comment]
Closed as #111 is merged:
The constructors of distribution specific estimators accept the argument `dtype: str = 'float32'`.
This dtype is passed on to all models and layers.
