### ISSUE TITLE
Investigate direct replacement of gradients

### ISSUE THREAD

**Issue by Hoeze** [theislab/batchglm#47]
It is possible to directly overwrite the gradient of Tensorflow operations.
[See also this example.](https://stackoverflow.com/a/43948872/2219819)

Instead of directly specifying the Jacobian for each combination of linker method and noise distribution, we could only exchange critical parts of the graph.
An example for this would be to directly specify the gradient of the NegativeBinomial distribution class.

This would eventually help as well to keep the gradient from getting NaN.

**Comment by davidsebfischer** [comment]
Done some time ago, in dev.
