### ISSUE TITLE
Model initialisation with reference model

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/batchglm#50]
Why is this https://github.com/theislab/batchglm/blob/154e8717cac10bfe15f4108d6c74bc248f346e20/batchglm/train/tf/nb_glm/estimator.py#L934 a random initialisation within a very small interval rather than a constant? I do not see the benefit of introducing this stochasticity but it can break reproducibility. As this additive in log space, I would just set the parameters that did not occur in the full model to zero?

**Comment by davidsebfischer** [comment]
I can modify it if we decide to change this.

**Comment by Hoeze** [comment]
I always used this to make sure that not all values in a tensor are equal, I just copied this over.
This can also be set to 0 I think...

**Comment by davidsebfischer** [comment]
Ok, I will try it and merge if it works.

**Comment by davidsebfischer** [comment]
Done in https://github.com/theislab/batchglm/commit/22853756191a119b16a3c1644f06404b7c668a82.
