### ISSUE TITLE
duplication of class definition TFEstimatorGraph

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/batchglm#62]
Appears in https://github.com/theislab/batchglm/blob/967e9173cec123aa33b90bec5eaf11a846ca6158/batchglm/train/tf/base/estimator_graph.py#L5 and https://github.com/theislab/batchglm/blob/2da429f895f7eb577a835da334f4ae146a9422ce/batchglm/train/tf/base/estimator.py#L15

**Comment by picciama** [comment]
@davidsebfischer We don't need this anymore since we depcreated tf1. I'd like to close it since @ilan-gold cleaned up all the tensorflow related code on dev after merging #120.

**Comment by picciama** [comment]
closing due to deprecation of tf1
