### ISSUE TITLE
Maybe mistake in formula

### ISSUE THREAD

**Issue by SabrinaRichter** [theislab/batchglm#67]
https://github.com/theislab/batchglm/blob/a7b579b14c821917b8d10391e9de8da05acebdf4/batchglm/train/tf/glm_nb/jacobians.py#L54
Maybe there should be an add instead of substract.

**Comment by davidsebfischer** [comment]
@SabrinaRichter can you check the maths again, please, I just got the comparison of analytical and auto-differentiation derived gradients to work and this suggests that the current form of the jacobian is correct and that replacing this substract by add introduces a fairly large error.
