### ISSUE TITLE
errors in unittests for graphs

### ISSUE THREAD

**Issue by SabrinaRichter** [theislab/batchglm#73]
After latest commits (on dev) unittests for graphs give errors:

For nb and norm:
Something about ValueError: Shape must be at least rank 2 but is rank 0 for 'MatrixSolveLs' (op: 'MatrixSolveLs') with input shapes: [], [2,3,1], [].

For beta: 
numpy.linalg.linalg.LinAlgError: Incompatible dimensions

**Comment by davidsebfischer** [comment]
I could not reproduce this, can you pull again and check whether this still occurs, please? If it does, just reopen the issue with the full error log.
