### ISSUE TITLE
Tutorial documentation error

### ISSUE THREAD

**Issue by charlotterich** [theislab/batchglm#76]
Many of your tutorials use 
`from batchglm.api.models.glm_nb import Simulator` 
to simulate data.

For diffxpy v0.4.2 (downloaded from pip), this should be 
`from batchglm.api.models.nb_glm import Simulator`

**Comment by charlotterich** [comment]
Just realised this is an issue for diffxpy, too many github pages open at once!

**Comment by davidsebfischer** [comment]
I'll fix this soon, thanks for the reminder!
